name: build

on: [push, pull_request]

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest]
        cc: [gcc, clang]
    steps:
      - uses: actions/checkout@v4
      - name: build
        run: make CC=${{ matrix.cc }}
      - name: test
        run: make test
